### ISSUE TITLE
Updates to installation and configuration

### ISSUE THREAD

**Issue by sax** [kwarter-cookbooks/twemproxy#1]
We have an internal fork of this cookbook that we just used to deploy twemproxy at Wanelo. Today we were looking at whether we could clean it up a bit and do a pull request to get it into your repository, but realized how much we changed.

For instance, we rewrote how some configs work, so you can set something like the following:

``` ruby
default['twemproxy']['configuration'] = {
  "config": {
    "hash": "fnv1_32",
    "hash_tag": "::",
    "distribution": "ketama",
    "timeout": 40,
    "auto_eject_hosts": false,
    "server_retry_timeout": 5000,
    "server_failure_limit": 3,
    "redis": true,
    "servers": [
      "#{ip}:#{port}:1 #{shard_name}",
      "#{ip}:#{port}:1 #{shard_name}"
    ]
  }
}
```

We also made some fixes to the installation from source, though we have not done any testing of the package recipe.

Would you be interested in this as a pull request?

cc: @richardiux

**Comment by dkoepke** [comment]
That'd be great. A lot of this was on my todo list. Feel free to submit a large PR, and we can see about pulling it apart, etc.

**Comment by sax** [comment]
Awesome! We'll try to get that in by early next week.

On Fri, May 3, 2013 at 1:42 PM, Daniel Koepke notifications@github.comwrote:

> That'd be great. A lot of this was on my todo list. Feel free to submit a
> large PR, and we can see about pulling it apart, etc.
> 
> Sent from my iPhone
> 
> On May 3, 2013, at 11:14 AM, Eric Saxby notifications@github.com wrote:
> 
> > We have an internal fork of this cookbook that we just used to deploy
> > twemproxy at Wanelo. Today we were looking at whether we could clean it up
> > a bit and do a pull request to get it into your repository, but realized
> > how much we changed.
> > 
> > For instance, we rewrote how some configs work, so you can set something
> > like the following:
> > 
> > default['twemproxy']['configuration'] = {
> > "config": {
> > "hash": "fnv1_32",
> > "hash_tag": "::",
> > "distribution": "ketama",
> > "timeout": 40,
> > "auto_eject_hosts": false,
> > "server_retry_timeout": 5000,
> > "server_failure_limit": 3,
> > "redis": true,
> > "servers": [
> > "#{ip}:#{port}:1 #{shard_name}",
> > "#{ip}:#{port}:1 #{shard_name}"
> > ]
> > }
> > }
> > We also made some fixes to the installation from source, though we have
> > not done any testing of the package recipe.
> > 
> > Would you be interested in this as a pull request?
> > 
> > cc: @richardiux
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/kwarter-cookbooks/twemproxy/issues/1#issuecomment-17416981
> .

## 

---

e s
